<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Hp" name="Test" tests="13" failures="3" timestamp="24 May 2022 09:53:00 GMT" time="0.196" errors="0">
  <testcase name="testcase1" time="0.017" classname="MockRetryConcept.Retry1"/>
  <testcase name="testcase2" time="0.002" classname="MockRetryConcept.Retry1">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.004" classname="MockRetryConcept.Retry1">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.006" classname="MockRetryConcept.Retry1">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.007" classname="MockRetryConcept.Retry1">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:147)
	at junit.framework.Assert.assertEquals(Assert.java:153)
	at MockRetryConcept.Retry1.testcase2(Retry1.java:15)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase name="Test1" time="0.025" classname="Retry.Test1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="Retry.Test1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="Retry.Test1">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.003" classname="Retry.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Retry.Test1.Test1(Test1.java:10)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.003" classname="Retry.Test1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="Retry.Test1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.002" classname="Retry.Test1">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.004" classname="Retry.Test1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Retry.Test1.Test2(Test1.java:16)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Test -->
